### ISSUE TITLE
question about usage

### ISSUE THREAD

**Issue by metinoktayboz** [dbry/lzw-ab#1]
hello, i am new at using c compilers. I could not run this program using git hash or cmd. Is that useable only mac/linux/visual studio? 

and i need to seperate WRITE_CODE part for my homework. I am studying on SoC acceleration about lzw. but when I seperate WRITE_CODE as a function in lzw-library, i had an error undeclared use "*dst".
What does *dst in there? I have spent hours to find it but i could not found. 

Thank you for your interest!

**Comment by dbry** [comment]
C programs must be compiled before they can be run, but there are free C compilers available for every platform.

WRITE_CODE is a C macro, and the `dst` in there must be a variable in the function that is invoking the macro, just like `bits`, `code_bits`, `shifter`, etc. The difference is that `dst` is actually an input parameter to the function, in this case declared on line 95.

Hope this helps and good luck on your project!
